### PR TITLE
Issue#58/validation

### PR DESCRIPTION
**Pull request by markiyanshvets**

### CODE REVIEW

**Review by tkristiansen — APPROVED** [review]
Ideally, we should not care about missing information for not enabled payment methods.. so if we don't use .AddMollie, we don't need to validate it. That might require to link registration of dependencies to .Add[Provider] as well.

These changes are at least an improvement, so PR approved, but do you have any thoughts about the above? (I think you mentioned something about disabled providers in our call earlier as well)

**Comment by markiyanshvets** [comment]
> Ideally, we should not care about missing information for not enabled payment methods.. so if we don't use .AddMollie, we don't need to validate it. That might require to link registration of dependencies to .Add[Provider] as well.
> 
> These changes are at least an improvement, so PR approved, but do you have any thoughts about the above? (I think you mentioned something about disabled providers in our call earlier as well)

It would be nice to refactor our payment providers as a full separated component to be able to include/exclude(in client - disable) payment providers, also provide to configuration something like "is available" which should be initialized after warmup DB (not sure), because we can't do this now explicitly. I think it is not in the scope of this task,  and implementing this can take a lot of time (like 3p)

**Comment by tkristiansen** [comment]
Agree that it is not within the scope of this.
The best would probably be to have each provider as a separate project / nuget package. Then the consumer would only include the relevant dependencies...

**Comment by markiyanshvets** [comment]
> Agree that it is not within the scope of this.
> The best would probably be to have each provider as a separate project / nuget package. Then the consumer would only include the relevant dependencies...

not sure about this option, we already have 7 packages and it is hard to monitor. I think it would be nice to have a mechanism to disable the payment provider and it will be enough for the first time

**Comment by tkristiansen** [comment]
> > Agree that it is not within the scope of this.
> > The best would probably be to have each provider as a separate project / nuget package. Then the consumer would only include the relevant dependencies...
> 
> not sure about this option, we already have 7 packages and it is hard to monitor. I think it would be nice to have a mechanism to disable the payment provider and it will be enough for the first time

Ok, might be too granular to split up. My main thought is that when a new payment provider is added, we don't want things to break for existing systems only because they upgrade to latest version. So any payment provider should "be disabled by default".

**Comment by markiyanshvets** [comment]
It is a good idea. So, we don't need to specify provider credentials and we can allow it on the admin panel, as I understand, but how to store secrets then?

**Comment by tkristiansen** [comment]
My main thought is when we see BCC Pay evolve further as an open source project. Other contributors might add a new payment provider. If e.g. Samvirk would update to the latest version, we don't want our behavior to change because somebody added a new provider.. (we should be open for extension and closed for modification)

If we would have to explicitly disable a certain provider, it means we need to change the code after upgrading to a BCC Pay with a new provider. To avoid it, all providers should be explicitly enabled. If they are encapsulated in a separate project, it is even more clear that they are not changing the behavior of the core / for applications not using them.

**Pull request merged**
